[project]
name = "phis-installer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "packaging>=25.0",
    "tomli>=2.3.0",
    "tomli-w>=1.0.0",
    "pip>=25.0.1",
    "setuptools>=75.3.2",
    "wheel>=0.45.1",
]
